#! /bin/bash

profile=$1

if [ ! $1 ]; then
	profile="prod"
fi

# 构建
mvn clean package -P $profile

# 上传
scp ./cache_service/target/cached.war root@www.scyok.com:/mnt/service/cached.war

# 远程执行
ssh root@www.scyok.com << remotessh
cd /mnt/service
rm -rf cached
service tomcat restart
exit
remotessh
